### ISSUE TITLE
Please specify tensorflow version tested on the homepage.

### ISSUE THREAD

**Issue by bushibushi** [davidsandberg/facenet#135]
I'm having trouble getting your code to work because of different tensorflow versions : 
`output = tf.nn.relu(inp) + tf.mul(alpha, -tf.nn.relu(-inp))
AttributeError: 'module' object has no attribute 'mul'`

This is while testing to validate : https://github.com/davidsandberg/facenet/wiki/Validate-on-lfw
(And by the way it should be ~/datasets/lfw/ instead of ~/datasets/lfw/raw)

**Comment by davidsandberg** [comment]
Fixed in 5725d9b7bad3c20b12c3965b4f4da0d296effd4f. Thanks!

**Comment by bushibushi** [comment]
Sorry, but the commit you linked to is not related to my issue in any way and I am still getting the issue after a pull today.

**Comment by bushibushi** [comment]
In order to see  if the issue is due to my tensorflow version, could you please run this for me to tell me your exact tensorflow version ?`python -c 'import tensorflow as tf; print(tf.__version__)'  # for Python 2
python3 -c 'import tensorflow as tf; print(tf.__version__)'  # for Python 3`

**Comment by davidsandberg** [comment]
Sorry, the commit hash was supposed to be fbe15bf414164e6c5e9c13e14dc12d4d3944d30b (i.e. update of the readme file).
The TF version i'm using is r0.12, installed using pip. I will run the command for you this evening.
However, it looks like your problem is due to an API change in TF r0.12 and should be fixed by changing instances of tf.mul to tf.multiply.

**Comment by bushibushi** [comment]
Ok, great ! Trying right now. Thanks !

**Comment by bushibushi** [comment]
Well I was indeed a bit too up-to-date. This is working now, thanks.
